# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

defaults:
  run:
    working-directory: .

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  webkit:
    name: Webkit with VoiceOver
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npx @guidepup/setup --ci
    - run: REPORT=true SNAPSHOT_UPDATE=1 npm run test:voiceover:webkit || true
    - uses: actions/upload-artifact@v3
      with:
        name: Webkit with VoiceOver
        path: output/voiceover-webkit
    
  chromium:
    name: Chromium with VoiceOver
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npx @guidepup/setup --ci
    - run: REPORT=true SNAPSHOT_UPDATE=1  npm run test:voiceover:chromium || true
    - uses: actions/upload-artifact@v3
      with:
        name: Chromium with VoiceOver
        path: output/voiceover-chromium
  
  firefox:
    name: Firefox with VoiceOver
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npx playwright install firefox
    - run: npm install
    - run: npx @guidepup/setup --ci
    - run: REPORT=true SNAPSHOT_UPDATE=1  npm run test:voiceover:firefox || true
    - uses: actions/upload-artifact@v3
      with:
        name: Firefox with VoiceOver
        path: output/voiceover-firefox

  PlaywrightMacOs:
    runs-on: macos-latest
    name: Playwright on MacOs
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: REPORT=true SNAPSHOT_UPDATE=1 npx npm-run-all -c --parallel test:webkit test:chromium test:firefox  || true
    - uses: actions/upload-artifact@v3
      with:
        name: Playwright on MacOs
        path: output/playwright-*/darwin-*-latest.json
  
  PlaywrightWindows:
    runs-on: windows-latest
    name: Playwright on Windows
    strategy:
      matrix:
        node-version: [14.x]
    outputs:
      result: ${{ steps.result.outputs.test }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npx playwright install-deps
      - run: npm install
      - run: REPORT=true SNAPSHOT_UPDATE=1 npx npm-run-all -c --parallel test:chromium || true
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: Playwright on Windows
          path: output/playwright-*/win32-*-latest.json
  
  PlaywrightUbuntu:
    runs-on: ubuntu-latest
    name: Playwright on Ubuntu
    strategy:
      matrix:
        node-version: [14.x]
    outputs:
      result: ${{ steps.result.outputs.test }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npx playwright install-deps
      - run: npm install
      - run: REPORT=true SNAPSHOT_UPDATE=1 npx npm-run-all -c --parallel test:webkit test:chromium test:firefox  || true
      - uses: actions/upload-artifact@v3
        with:
          name: Playwright on Ubuntu
          path: output/playwright-*/linux-*-latest.json
