name: NVDA

on:
  workflow_call

jobs:
        
  nvda:
  
    name: NVDA
    
    runs-on: windows-latest

    steps:

    - name: Get last release
      id: get-last-release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: nvaccess/nvda
        excludes: prerelease, draft
    
    - name: Cache NVDA
      id: cache-nvda
      uses: actions/cache@v3
      with:
        path: nvda
        key: ${{ runner.os }}-nvda-${{ steps.get-last-release.outputs.release }}
    - name: Set up Python 3.7 x86
      if: steps.cache-nvda.outputs.cache-hit != 'true'
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
        architecture: x86
    - name: Checkout NVDA
      if: steps.cache-nvda.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: nvaccess/nvda
        submodules: true
        path: nvda
        ref: ${{ steps.get-last-release.outputs.release }}
    - name: Prepare NVDA's source tree
      if: steps.cache-nvda.outputs.cache-hit != 'true'
      run: |
        cd nvda
        scons source
      shell: cmd
    - name: Start NVDA
      run: |
        cd nvda
        runnvda -m --debug-logging
        ping 127.0.0.1 /n 20
      shell: cmd
    - name: Quit NVDA
      run: |
        cd nvda
        runnvda -q
        ping 127.0.0.1 /n 20
      shell: cmd
    - name: Upload log
      uses: actions/upload-artifact@v3
      with:
        name: nvda-log
        path: nvda\source\nvda.log
