# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Orca

defaults:
  run:
    working-directory: .

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
    
  chromium:
    name: Chromium with Orca
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get install sox -y
          sudo apt-get install speech-dispatcher -y
          sudo apt-get install espeak -y
          sudo apt-get install gnome-orca -y
      - run: orca --version
