# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

defaults:
  run:
    working-directory: .

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  webkit:
    name: Webkit with VoiceOver
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - run: screencapture -v -C -k -T0 -V 10 foo.mov
    - uses: actions/upload-artifact@v3
      with:
        name: Screencapture
        path: foo.mov
  
