name: Screencapture

defaults:
  run:
    working-directory: .

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  webkit:
    name: Webkit with VoiceOver
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - run: screencapture -T0 -V 10 foo.mov
    - uses: actions/upload-artifact@v3
      with:
        name: Screencapture
        path: foo.mov
  
